# Generated by Django 4.2.6 on 2023-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="input_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("player_POS", models.CharField(max_length=2)),
                ("player_Height", models.DecimalField(decimal_places=2, max_digits=4)),
                ("player_Weight", models.PositiveIntegerField()),
                ("player_40Yard", models.DecimalField(decimal_places=2, max_digits=4)),
                ("player_BenchPress", models.PositiveIntegerField()),
                ("player_Vert", models.DecimalField(decimal_places=1, max_digits=4)),
                ("player_Broad", models.PositiveIntegerField()),
                ("player_Shuttle", models.DecimalField(decimal_places=2, max_digits=4)),
                ("player_3Cone", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
