# Generated by Django 4.2.6 on 2023-10-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine_web', '0004_alter_input_data_prediction_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
